import { Comic_Neue } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import Footer from '../Components/Footer';
import ReviewPrompt from '../Components/ReviewPrompt';
import AdminNotifications from '../Components/AdminNotifications';

const comicNeue = Comic_Neue({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${comicNeue.className} antialiased`}
      >
        {children}
        <Toaster />
        <ReviewPrompt />
        <AdminNotifications />
        <Footer />
      </body>
    </html>
  );
}
